default:
	nvcc -O3 -o pa3p5 pa3p5.cu
	nvcc -O3 -o pa3p4 pa3p4.cu
	nvcc -O3 -o pa3p3 pa3p3.cu
	nvcc -O3 -o pa3p2 pa3p2.cu
	nvcc -O3 -o pa3p1 pa3p1.cu

run:
	./pa3p1
	./pa3p2
	./pa3p3
	./pa3p4
	./pa3p5
